### ISSUE TITLE
traspasar modelo de datos a BD

### ISSUE THREAD

**Issue by gogigopuduh** [cedit/duhatao-api#1]
Diego el modelo lo revisamos el dia sábado pasado, debes pasar el modelo a la BD que usaremos. creo que seria Postgress.. @rcisterna  confirma si es ese el motor u otro. ;D

cc: @elwla  comparte acá el modelo revisado en la ultima reunión.

**Comment by thexcats** [comment]
El modelo está listo en la base de datos las migraciones están creadas hasta lo que han pedido hasta el momento la base de datos está en el archivo projectdb
Saludos
El 30 may. 2016 11:56, Rodrigo Venegas <notifications@github.com> escribió:Diego el modelo lo revisamos el dia sábado pasado, debes pasar el modelo a la BD que usaremos. creo que seria Postgress.. @rcisterna  confirma si es ese el motor u otro. ;D

cc: Wladirmir comparte acá el modelo revisado en la ultima reunión.

**Comment by rcisterna** [comment]
El ORM de Laravel es independiente, así que debería funcionar tanto en PostgreSQL como en cualquier otro SGBD relacional. De todas formas, las pruebas en desarrollo se hacen sobre PostgreSQL, que es lo que la máquina virtual de vagrant está configurada para instalar.

@thexcats, falta que @elwla suba las modificaciones a la base de datos (mañana estarán en el repo). Después de eso, @gogigopuduh irá indicando acá (mediante nuevos issues) las cosas que debes hacer durante el mes. A medida que vayamos desarrollando, @migueee irá haciendo las pruebas unitarias y de integración, para corroborar que todo funciona como corresponde.

**Comment by elwla** [comment]
las modificaciones están arriba. Debo ir agregando las restricciones de los campos.

**Comment by gogigopuduh** [comment]
@elwla puedes subir una version imagen del modelo? no hay caso no puedo importarlo a StarUML
