### ISSUE TITLE
Tabla Indicacion

### ISSUE THREAD

**Issue by thexcats** [cedit/duhatao-api#12]
consulta para el que hizo el MER, la tabla indicacion tiene un atributo que se llama otras_actividades, que tipo es ?, supongo que es VARCHAR pero de cuanta es la cantidad ? espero sus respuestas, @rcisterna @elwla @gogigopuduh @migueee

**Comment by elwla** [comment]
Sorry, varchar(512)
Cualquier duda del modelo, conmigo.

Saludos

**Comment by thexcats** [comment]
estimado otra consulta, en la tabla ciclo_vital, el atributo tipo_consulta es varchar, cual es la cantidad para ese atributo ??


Saluda Atte.
Diego Parraguez+56 9 511 938 15Alumno Pre-grado Universidad del Bío - Bío Escuela Ingeniería Civil en Informática 



Date: Wed, 22 Jun 2016 14:32:34 -0700

**Comment by elwla** [comment]
Es 25.

Mañana revisaré en profundidad el modelo, para agregar lo que falte.

Saludos

**Comment by thexcats** [comment]
@elwla  Otra consulta mas, en la tabla ficha_general, el atributo que se pasa como llave foranea que se llama fecha_id, ese atributo de que tabla se pasa ?
