### ISSUE TITLE
Tabla Ficha_General

### ISSUE THREAD

**Issue by thexcats** [cedit/duhatao-api#13]
Consulta, en la tabla ficha_general hay un atributo llamado fecha_id que se pasa como llave foranea, de que tabla proviene ese atributo ??? estoy esperando la respuesta para terminar de crear los modelos, controladores y tablas

@rcisterna 
@elwla 
@gogigopuduh 
@migueee 
@cedit/desarrolladores-duhatao

**Comment by elwla** [comment]
Hola.
Disculpa haber demorado tanto. Es un error en el atributo, no debería ser FK, es un valor propio de la tabla, mañana lo corregiré y subiré de nuevo. Saludos
