### ISSUE TITLE
crear CRUD paciente

### ISSUE THREAD

**Issue by gogigopuduh** [cedit/duhatao-api#2]
crear CRUD paciente con sus validaciones, interacciones, relaciones y reglas de negocio

**Comment by gogigopuduh** [comment]
favor comentar avances o problemas en que este estancado.

cc: @rcisterna

**Comment by thexcats** [comment]
el grud del paciente esta creado, aun tengo que modificar unas lineas para los demas modelos, tenia problemas con las claves foraneas, me guie con la documentacion de laravel, a la tarde subire los commit y hare el push y pull al proyecto
